name: CI

on:
  push:
    branches:
      - main
      - 101562530-Nandninand
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: echo "CI working successfully"
